version: "3"
services:
  frontend:
    image: geoatzen/atzengisfrontend
    container_name: frontendatzengis
    build: 
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
     - dockerdata:/usr/src/app/mydockerdata

#imagename://servicename:zweiterPort

  backendgeoatzen:
    image: geoatzen/atzengisbackend
    container_name: backendatzengis
    build: 
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    volumes:
     - dockerdata:/usr/src/app/mydockerdata

volumes:
  dockerdata:
