version: "3"
services:
  frontend:
    container_name: frontendatzengis
    image: geoatzen/frontendatzengis
    build: 
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000 # forward webserver on 3000-http port
    volumes:
     - dockerdata:/usr/src/app/mydockerdata

#imagename://servicename:zweiterPort

  backendgeoatzen:
    image: geoatzen/backendatzengis
    container_name: backendatzengis
    build: 
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    volumes:
     - dockerdata:/usr/src/app/mydockerdata

volumes:
  dockerdata:
